# Font rendering y Hardware
WLR_NO_HARDWARE_CURSORS=1
FREETYPE_PROPERTIES="cff:no-stem-darkening=0 autofitter:no-stem-darkening=0"

# Video acceleration
LIBVA_DRIVER_NAME=nvidia
NVD_BACKEND=direct
VDPAU_DRIVER=nvidia
__GLX_VENDOR_LIBRARY_NAME=nvidia
