#
# $PARU_CONF
# /etc/paru.conf
# ~/.config/paru/paru.conf
#
# See the paru.conf(5) manpage for options
#
# GENERAL OPTIONS
#
[options]
PgpFetch
Devel
Provides
BottomUp
SudoLoop
RemoveMake
CleanAfter
CombinedUpgrade
BatchInstall
UpgradeMenu
NewsOnUpgrade
SaveChanges
SkipReview
DevelSuffixes = -git -cvs -svn -bzr -darcs -always -hg -fossil
SortBy = votes
SearchBy = name-desc
CompletionInterval = 7
#AurOnly
#RepoOnly
#UseAsk
#LocalRepo
#Chroot
#Sign
#SignDb
#KeepRepoCache
#NoCheck
#InstallDebug
#Redownload
#Rebuild
#
# Binary OPTIONS
#
[bin]
FileManager = yazi
Bat = bat
#MFlags = --skippgpcheck
#Sudo = doas
#BatFlags = --style=plain
#Pager = less
#PreBuildCommand =
