###################
### KEYBINDINGS ###
###################

# Programs
bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, SPACE, exec, $menu

# System
bind = $mainMod Shift, R, exec, hyprctl reload
bind = $mainMod, M, exec, wlogout -b 5
bind = $mainMod Shift, Q, exec, $lock
bind = $mainMod, F11, fullscreen,

# Window manangement
bind = $mainMod, Q, killactive,
bind = $mainMod, V, togglefloating,

bind = $mainMod, h, movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d

bind = $mainMod Shift, H, movewindow, l
bind = $mainMod Shift, J, movewindow, d
bind = $mainMod Shift, K, movewindow, u
bind = $mainMod Shift, L, movewindow, r

bind = $mainMod, TAB, togglespecialworkspace, magic
bind = $mainMod SHIFT, TAB, movetoworkspace, special:magic

bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bind = $mainMod, F, layoutmsg, swapwithmaster
bind = $mainMod Shift, F, layoutmsg, focusmaster

# REDIMENSIONAR ventanas
binde = $ctrlMod, h, resizeactive, -30 0
binde = $ctrlMod, l, resizeactive,  30 0
binde = $ctrlMod, k, resizeactive,  0 -30
binde = $ctrlMod, j, resizeactive,  0  30

# Workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bind = $mainMod Shift, 1, movetoworkspace, 1
bind = $mainMod Shift, 2, movetoworkspace, 2
bind = $mainMod Shift, 3, movetoworkspace, 3
bind = $mainMod Shift, 4, movetoworkspace, 4
bind = $mainMod Shift, 5, movetoworkspace, 5
bind = $mainMod Shift, 6, movetoworkspace, 6
bind = $mainMod Shift, 7, movetoworkspace, 7
bind = $mainMod Shift, 8, movetoworkspace, 8
bind = $mainMod Shift, 9, movetoworkspace, 9
bind = $mainMod Shift, 0, movetoworkspace, 10

# Audio
bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# Screenshots
bind = , Print, exec, hyprshot -m output --raw | satty --filename - --output-filename ~/Pictures/Screenshots/$(date '+%Y%m%d-%H%M%S').png
bind = $mainMod, Print,  exec, hyprshot -m region --clipboard-only
bind = $mainMod, F12, exec, hyprshot -m region --raw | satty --filename - --output-filename ~/Pictures/Screenshots/$(date '+%Y%m%d-%H%M%S').png --copy-command wl-copy
