general {
    gaps_in = 5
    gaps_out = 9
    border_size = 2

    # Colores
    col.active_border = $blue
    col.inactive_border = $surface0

    # Comportamiento
    resize_on_border = true
    allow_tearing = false
    layout = master
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    mouse_move_enables_dpms = false
    key_press_enables_dpms = false
    allow_session_lock_restore = false
}
