################
### OUTPUT ###
################
monitor=,preferred,auto,1

# Si tienes múltiples monitores, usa esto:
# monitor=HDMI-A-1,1920x1080@60,0x0,1
# monitor=DP-1,2560x1440@165,-1920x0,1
# workspace=1,monitor:HDMI-A-1
# workspace=2,monitor:DP-1
