################
### WINDOWS ###
###############

group {
    col.border_active = $blue
    col.border_inactive = $surface1
}

#############
### THEME ###
#############

animations {
    enabled = yes

    # Define tus beziers
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    bezier = easeInOutQuad, 0.45, 0, 0.55, 1

    # Aplica animaciones
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, easeInOutQuad
}

decoration {
    rounding = 12

    active_opacity = 1.0
    inactive_opacity = 0.9

    shadow {
        enabled = true
        range = 15
        render_power = 3
        color = rgba(1a1a1aee)
    }

    blur {
        enabled = true
        size = 5
        passes = 3
        vibrancy = 0.1696
        special = true
    }
}
