# APLICACIONES
$terminal = kitty
$fileManager = nemo
$menu = bash ~/.config/rofi/launch.sh
$emojiSelector = bash ~/.config/rofi/emoji.sh
$clipboardSelector = bash ~/.config/rofi/clipboard.sh
$lock = hyprlock
$browser = brave

# TECLAS PRINCIPALES
$mainMod = SUPER
$ctrlMod = Control_L
$altMod = ALT_L

# COLORS
$mauve = rgba(c6a0f6ff)
$blue = rgba(8aadf4ff)
$red = rgba(ed8796ff)
$green = rgba(a6da95ff)
$peach = rgba(f5a97fff)

# Backgrounds
$mantle = rgba(1a1a1aee)
$base = rgba(24273aff)
$surface0 = rgba(49495aff)
$surface1 = rgba(565a7aff)
$surface2 = rgba(6d7899ff)

# Text
$text = rgba(cad1d9ff)
$subtext0 = rgba(a5adcbff)
$subtext1 = rgba(b8c5d6ff)
