#####################
### WINDOWS RULES ###
#####################

windowrule {
    name = wofi-config
    match:class = ^(wofi)$
    float = on
    size = 50% 50%
    center = on
}

windowrule {
    name = pavucontrol-config
    match:class = ^(pavucontrol)$
    float = on
    size = 80% 80%
}

# NOTIFICACIONES (sticky)
windowrule {
    name = notifications
    match:class = ^(mako)$
    pin = on
    float = on
}
